---
- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-linters

- job:
    name: flock-devstack-ha
    parent: flock-devstack-base-min
    required-projects:
      - openstack/barbican
      - openstack/python-barbicanclient
      - starlingx/config
      - starlingx/fault
      - starlingx/integ
      - starlingx/metal
      - starlingx/nfv
      - starlingx/update
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        fm-common: true
        fm-api: true
        sm-common: true
        sm-db: true
        sm-daemon: true
        sm-client: true
        sm-tools: true
        sm-api: true
        sm-eru: true
        sm-watchdog: true
        mysql: false
        postgresql: true
        tls-proxy: false
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican
        config: https://opendev.org/starlingx/config
        fault: https://opendev.org/starlingx/fault
        ha: https://opendev.org/starlingx/ha
        integ: https://opendev.org/starlingx/integ
        metal: https://opendev.org/starlingx/metal
        nfv: https://opendev.org/starlingx/nfv
        update: https://opendev.org/starlingx/update
